# Generated by Django 5.2.1 on 2025-05-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fisrt_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
