# Generated by Django 5.2.1 on 2025-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_fisrt_name_employee_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
